services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports: ["3306:3306"]
    volumes: [ db_data:/var/lib/mysql ]
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes","--save","", "--requirepass", "${REDIS_PASSWORD}"]
    ports: ["6379:6379"]
    environment:
      TZ: Asia/Seoul
    volumes: [ redis_data:/data ]
    healthcheck:
      test: ["CMD","sh","-lc","redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      DB_URL: "${MYSQL_URL}"
      DB_USER: "${MYSQL_USER}"
      DB_PASS: "${MYSQL_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports: ["1220:1220"]
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
